apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend 
  labels:
    app: guestbook
    tier: frontend #It allow to ReplicaSet know who are its children
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend #It allow to Pods know who are the their ReplicaSet 
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
